baseURL = "https://kruyt.org/"
disablePathToLower = true
languageCode = "en-us"
title = "Dennis Kruyt"
theme = "hugo-papermod"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
    post = "/:filename/"
    code = "/:filename/"
